name: CI

on:
  push:
    branches:
      - "feature/**"
      - "dev"

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t blogora-image:1.0.0 .

      - name: Run pylint
        run: |
          docker run --rm \
          -v "${{ github.workspace }}:/app" \
          -w /app \
          blogora-image:1.0.0 \
          bash tools/pylint.sh